vision:
  scale: 1.0
  gamma: 3.0
  num_colors: 2
  smooth_kernel_size: 5
  roi_from_top: 160
  roi_from_bot: 60
  color1_thresh_lb: 0
  color2_thresh_lb: 0
  color3_thresh_lb: 0
  color1_thresh_ub: 255
  color2_thresh_ub: 255
  color3_thresh_ub: 255
  threshold_adaptive: true
  adaptive_threshold_method: 1 # 0=ADAPTIVE_THRESH_MEAN_C; 1=ADAPTIVE_THRESH_GAUSSIAN_C
  adaptive_threshold_mean_subtract: 2.0
  adaptive_threshold_block_size: 11
  threshold_type: 0 # 0=THRESH_BINARY; 8=THRESH_BINARY|THRESH_OTSU; 16=THRESH_BINARY|THRESH_TRIANGLE; 1=THRESH_BINARY_INV; 9=THRESH_BINARY_INV|THRESH_OTSU; 17=THRESH_BINARY_INV|THRESH_TRIANGLE;
  color_conversion: 52 # 40=COLOR_BGR2HSV; 44=COLOR_BGR2Lab; 52=COLOR_BGR2HLS; 82=COLOR_BGR2YUV
  